version: "3"
services:
  web:
    build: ./docker/nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - .:/var/www/html
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: boardgame-reviews
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 80:80
    restart: always
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
volumes:
  mysql-data:
