branch-defaults:
  master:
    environment: develop
    group_suffix: null
global:
  application_name: boardgame-reviews
  branch: null
  default_ec2_keyname: ssh
  default_platform: Multi-container Docker 18.09.9-ce (Generic)
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
