version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.1-apache-node-browsers
      - image: circleci/mysql:5.7

    environment:
      - DB_CONNECTION: mysql_testing

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo docker-php-ext-install pdo_mysql

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "composer.json" }}
      #       - v1-dependencies-

      - run:
          name:
          command: |
            ls
            cd boardgame-reviews
            composer install -n --prefer-dist --no-dev

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: php artisan migrate

      - run: php ./vendor/bin/phpunit

  build_image:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install aws cli
          command: |
            apk add --no-cache --update py-pip
            pip install awscli
      - run:
          name: aws configure list
          command: |
            aws configure list
            ls
      - run:
          name: login ecr
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - run:
          name: build image
          command: |
            docker build -t ${ECR_DOMAIN}:$CIRCLE_SHA1 -t ${ECR_DOMAIN}:latest ./docker/php/
      - run:
          name: Push docker image
          command: |
            docker push ${ECR_DOMAIN}:latest
      - run:
          name: Install awsebcli
          command: |
            pip install --upgrade pip
            pip install awsebcli --user
            eb --version
      - run:
          name: eb deploy
          command: |
            cd boardgame-reviews
            eb deploy
workflows:
  version: 2
  test:
    jobs:
      - build
      - build_image:
          requires:
            - build
          filters:
            branches:
              only: deploy
