version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.1-fpm
      - image: circleci/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        envirionment:
          - APP_DEBUG: true
          - APP_ENV: circle
          - DB_CONNECTION: circle_test
          - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_setup
          command: |
            sudo apt-get update \
            && sudo apt-get install -y libpq-dev \
            && sudo apt-get install -y libpq-dev libzip-dev \
            && sudo docker-php-ext-install pdo_mysql pdo_pgsql \
            && sudo docker-php-ext-install zip

      - run:
          name: composer install
          command: cd /usr/bin && curl -s http://getcomposer.org/installer |
            sudo php && ln -s /usr/bin/composer.phar /usr/bin/composer

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: migration
          command: php artisan migrate --env=circle

      - run:
          name: env_copy
          command: rm .env.testing && ln -s .env.circle .env.testing
