version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.1-fpm
        environment:
          - DB_HOST=127.0.0.1
          - DB_PORT=3306
          - DB_DATABASE=circleci
          - DB_USERNAME=circleci
          - DB_PASSWORD=circleci
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ROOT_PASSWORD=circleci
          - MYSQL_DATABASE=circleci
          - MYSQL_USER=circleci
          - MYSQL_PASSWORD=circleci

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_setup
          command: |
            sudo apt-get update \
            && sudo apt-get install -y libpq-dev \
            && sudo apt-get install -y libpq-dev libzip-dev \
            && sudo docker-php-ext-install pdo_mysql pdo_pgsql \
            && sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./boardgame-reviews/composer.json" }}
            - v1-dependencies-

      - run: ls
      - run:
          name: composer install
          command: composer install -n --prefer-dist --no-dev --working-dir=./boardgame-reviews

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "./boardgame-reviews/composer.json" }}

      - run:
          name: migration
          command: php ./boardgame-reviews/artisan migrate --force

      - run:
          name: env_copy
          command: rm ./boardgame-reviews/.env.testing && ln -s .env.circle .env.testing
