version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.1-fpm
      - image: circleci/mysql:5.7
        command: mysqld --default-authentication-plugin=mysql_native_password
        envirionment:
          - APP_DEBUG: true
          - APP_ENV: circle
          - DB_CONNECTION: circle_test
          - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_setup
          command: |
            sudo apt-get update \
            && sudo apt-get install -y libpq-dev \
            && sudo apt-get install -y libpq-dev libzip-dev \
            && sudo docker-php-ext-install pdo_mysql pdo_pgsql \
            && sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./boardgame-reviews/composer.json" }}
            - v1-dependencies-

      - run: ls
      - run:
          name: composer install
          command: composer install -n --prefer-dist --no-dev --working-dir=./boardgame-reviews

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "./boardgame-reviews/composer.json" }}

      - run:
          name: migration
          command: php ./boardgame-reviews/artisan migrate --env=circle

      - run:
          name: env_copy
          command: rm ./boardgame-reviews/.env.testing && ln -s .env.circle .env.testing
