version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.1-apache-node-browsers
      - image: circleci/mysql:5.7

    environment:
      - DB_CONNECTION: circle_test

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install php module
          command: |
            sudo docker-php-ext-install pdo_mysql
            sudo apt-get update 
            sudo apt-get install -y libjpeg-dev libfreetype6-dev 
            sudo docker-php-ext-configure gd 
            sudo docker-php-ext-install -j$(nproc) gd

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./boardgame-reviews/composer.json" }}
            - v1-dependencies-

      - run:
          name: install package
          command: |
            cd boardgame-reviews
            composer install -n --prefer-dist --dev

      - save_cache:
          paths:
            - ./boardgame-reviews/vendor
          key: v1-dependencies-{{ checksum "./boardgame-reviews/composer.json" }}

      # - run:
      #     name: base64 decode env file
      #     # ファイルに改行が含まれているので`-i`オプションを付ける
      #     command: |
      #       echo $ENV_FILE | base64 -di > .env.testing
      #       cp .env.testing .env

      - run:
          name: migrate
          command: |
            cd boardgame-reviews
            php artisan migrate --force

      - run:
          name: test
          command: |
            cd boardgame-reviews
            ./vendor/bin/phpunit

  build_image:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install aws cli
          command: |
            apk add --no-cache --update py-pip
            pip install awscli
      - run:
          name: aws configure list
          command: |
            aws configure list
            ls
      - run:
          name: Install awsebcli
          command: |
            pip install --upgrade pip
            pip install awsebcli --user
            eb --version
      - run:
          name: eb deploy
          command: |
            cd boardgame-reviews
            eb deploy
workflows:
  version: 2
  test:
    jobs:
      - build
      - build_image:
          requires:
            - build
          filters:
            branches:
              only: deploy
