version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.1-fpm
        environment:
          - DB_HOST=127.0.0.1
          - DB_PORT=3306
          - DB_DATABASE=circleci
          - DB_USERNAME=circleci
          - DB_PASSWORD=circleci
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ROOT_PASSWORD=circleci
          - MYSQL_DATABASE=circleci
          - MYSQL_USER=circleci
          - MYSQL_PASSWORD=circleci

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_setup
          command: |
            sudo apt-get update \
            && sudo apt-get install -y libpq-dev \
            && sudo apt-get install -y libpq-dev libzip-dev \
            && sudo docker-php-ext-install pdo_mysql pdo_pgsql \
            && sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./boardgame-reviews/composer.json" }}
            - v1-dependencies-

      - run: ls
      - run:
          name: composer install
          command: composer install -n --prefer-dist --no-dev --working-dir=./boardgame-reviews

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "./boardgame-reviews/composer.json" }}

      - run:
          name: migration
          command: php ./boardgame-reviews/artisan migrate --force

      - run:
          name: env_copy
          command: rm ./boardgame-reviews/.env.testing && ln -s .env.circle .env.testing
  build_image:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install aws cli
          command: |
            apk add --no-cache --update py-pip
            pip install awscli
      - run:
          name: aws configure list
          command: |
            aws configure list
            ls
      - run:
          name: login ecr
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - run:
          name: build image
          command: |
            docker build -t ${ECR_DOMAIN}:$CIRCLE_SHA1 -t ${ECR_DOMAIN}:latest .
      - run:
          name: Push docker image
          command: |
            docker push ${ECR_DOMAIN}:$CIRCLE_SHA1
            docker push ${ECR_DOMAIN}:latest
workflows:
  version: 2
  test:
    jobs:
      - build
      - build_image:
          requires:
            - build
          filters:
            branches:
              only: master
