version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.1-fpm
      - image: circleci/mysql:5.7
        command: mysqld --default-authentication-plugin=mysql_native_password
        envirionment:
          - APP_DEBUG: true
          - APP_ENV: circle
          - DB_CONNECTION: circle_test
          - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test_setup
          command: |
            cd /usr/bin && curl -s http://getcomposer.org/installer | php && ln -s /usr/bin/composer.phar /usr/bin/composer |
            sudo apt-get update \&& apt-get install -y \git \zip \unzip \vim |
            curl -sL https://deb.nodesource.com/setup_10.x | bash - |
            sudo apt-get install -y nodejs |
            sudo apt-get update \&& apt-get install -y libpq-dev \  && apt-get install -y libpq-dev libzip-dev \  && docker-php-ext-install pdo_mysql pdo_pgsql \  && docker-php-ext-install zip

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: composer install
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: migration
          command: php artisan migrate --env=circle

      - run:
          name: env_copy
          command: rm .env.testing && ln -s .env.circle .env.testing
